name: Deploy theme to multiple sites

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      sites:
        description: 'Sites to deploy (comma-separated: kyoto,osaka,tokyo or "all")'
        required: true
        default: 'kyoto'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        site:
          - name: kyoto
            ftp_server_secret: FTP_SERVER_KYOTO
            ftp_username_secret: FTP_USERNAME_KYOTO
            ftp_password_secret: FTP_PASSWORD_KYOTO
            remote_dir_secret: FTP_REMOTE_DIR_KYOTO
            url: https://kyoto.361project.com
          - name: osaka
            ftp_server_secret: FTP_SERVER_OSAKA
            ftp_username_secret: FTP_USERNAME_OSAKA
            ftp_password_secret: FTP_PASSWORD_OSAKA
            remote_dir_secret: FTP_REMOTE_DIR_OSAKA
            url: https://osaka.361project.com
          - name: tokyo
            ftp_server_secret: FTP_SERVER_TOKYO
            ftp_username_secret: FTP_USERNAME_TOKYO
            ftp_password_secret: FTP_PASSWORD_TOKYO
            remote_dir_secret: FTP_REMOTE_DIR_TOKYO
            url: https://tokyo.361project.com
    
    steps:
      - name: Check if site should be deployed
        id: check
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo "should_deploy=true" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.inputs.sites }}" == "all" ]]; then
            echo "should_deploy=true" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.inputs.sites }}" == *"${{ matrix.site.name }}"* ]]; then
            echo "should_deploy=true" >> $GITHUB_OUTPUT
          else
            echo "should_deploy=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Checkout
        if: steps.check.outputs.should_deploy == 'true'
        uses: actions/checkout@v4

      - name: Prepare artifact for ${{ matrix.site.name }}
        if: steps.check.outputs.should_deploy == 'true'
        run: |
          mkdir -p dist
          echo "Preparing theme for ${{ matrix.site.name }} site"
          rsync -a --delete --exclude='.git' --exclude='dist' --exclude='.github' ./ ./dist/361theme/

      - name: Deploy to ${{ matrix.site.name }} via FTPS
        if: steps.check.outputs.should_deploy == 'true'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets[format('{0}', matrix.site.ftp_server_secret)] }}
          username: ${{ secrets[format('{0}', matrix.site.ftp_username_secret)] }}
          password: ${{ secrets[format('{0}', matrix.site.ftp_password_secret)] }}
          protocol: ftps
          local-dir: dist/361theme/
          server-dir: ${{ secrets[format('{0}', matrix.site.remote_dir_secret)] }}

      - name: Verify deployment for ${{ matrix.site.name }}
        if: steps.check.outputs.should_deploy == 'true'
        run: |
          echo "✅ Theme deployed to ${{ matrix.site.url }}"
          echo "🔗 Check: ${{ matrix.site.url }}/wp-content/themes/361theme/"