name: Release on tag

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create zip from tag
        run: |
          set -e
          VERSION="${GITHUB_REF_NAME}"
          mkdir -p dist
          git archive --format=zip --output "dist/361theme-${VERSION}.zip" --prefix=361theme/ "${VERSION}"
          ls -lh dist

      - name: Create GitHub Release and upload asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          generate_release_notes: true
          files: |
            dist/361theme-${{ github.ref_name }}.zip
